version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    network_mode: service:db
    volumes:
      - ..:/home/statink/stat.ink:cached  
    command: sleep infinity
    user: statink
  fpm:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    network_mode: service:db
    volumes:
      - ..:/home/statink/stat.ink:cached  
    command: /opt/remi/php80/root/usr/sbin/php-fpm --nodaemonize
  h2o:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    network_mode: service:db
    volumes:
      - ..:/home/statink/stat.ink:cached  
    command: h2o -m master -c /etc/h2o/h2o.conf 
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: statink
      POSTGRES_DB: statink
      POSTGRES_PASSWORD: statink

volumes:
  postgres-data:
